## 다시보는 초난감 DAO
예외상황에 대한 처리 개선 작업이 필요하다.

### 3.1.1 예외처리 기능을 갖춘 DAO
> ***JDBC 수정 기능의 예외처리 코드***

🔽 JDBC API를 이용한 DAO 코드인 deleteAll()
```java
public void deleteAll() throws SQLException {
  Connection c = dataSource.getConnection();

  // 여기서 예외가 발생하면 바로 메소드 실행이 중단된다.
  PreparedStatement ps = c.prepareStatement("delete from users");
  ps.executeUpdate();

  ps.close();
  c.close();
}
```
- PreparedStatement를 처리하는 중에 예외가 발생하면 바로 메소드를 빠져나가게 된다.
- close() 메소드가 실행되지 않아서 제대로 리소스가 반환되지 않을 수 있다.
- 일반적으로 서버에서는 **제한된 개수**의 DB 커넥션을 만들어서 **재사용 가능한 풀**로 관리한다.
- 오류가 날 때마다 반환되지 못한 Connection이 쌓이면, 어느 순간 커넥션 풀에 리소스가 고갈될 수 있다.

<br/>

🔽 예외 발생 시에도 리소스를 반환하도록 수정한 deleteAll()
```java
public void deleteAll() throws SQLException {
  Connection c = null;
  PreparedStatement ps = null;

  try { // 예외가 발생할 가능성이 있는 코드를 모두 try 블록으로 묶어준다.
    c = dataSource.getConnection();
    ps = c.preparedStatement("delete from users");
    ps.executeUpdate();
  } catch (SQLException e) {
    // 예외가 발생했을 때 부가적인 작업을 해줄 수 있도록 catch 블록을 둔다.
    // 아직은 예외를 다시 메소드 밖으로 던지는 것밖에 없다.
  } finally { // try 블록에서 예외가 발생했을 때나 안 했을 때나 모두 실행된다.
    if(ps != null) {
      try {
        ps.close();
      } catch (SQLException e) {
        // ps.close() 메소드에서도 예외가 발생할 수 있기 때문에 이를 잡아줘야 한다.
        // 그렇지 않으면 Connection을 close() 하지 못하고 메소드를 빠져나갈 수 있다.
      }
    }
    if (c != null) {
      try {
        c.close(); // Connection 반환
      } catch (SQLException e) {
      }
    }
  }
}
```
- **finally** : try 블록을 수행한 후에 예외가 발생하든 아니든 반드시 실행되는 코드를 넣을 때 사용한다.
- close()를 사용할 수 있는 변수가 달라질 수 있기 때문에 finally에서는 반드시 c와 ps가 null이 아닌지 먼저 확인한 후 close() 메소드를 호출해야 한다.
- 예외가 발생한 경우에 로그를 남기는 등의 부가작업이 필요할 수 있으니 catch 블록은 일단 만들어두는 편이 좋다.

<br/>

> ***JDBC 조회 기능의 예외처리***

🔽 JDBC 예외처리를 적용한 getCount() 메소드
```java
public int getCount() throws SQLException {
  Connection c = null;
  PreparedStatement ps = null;
  ResultSet rs = null;

  try {
    c = dataSource.getConnection();

    ps = c.prepareStatement("select count(*) from users");

    // Result도 다양한 SQLException이 발생할 수 있는 코드이므로 try 블록 안에 둔다.
    rs = ps.executeQuery();
    rs.next();
    return rs.getInt(1);
  } catch (SQLException e) {
    throw e;
  } finally {
    if (rs != null) { // 만들어진 ResultSet을 닫아주는 기능. close()는 만들어진 순서의 반대로 하는 것이 원칙이다.
      try {
        rs.close();
      } catch (SQLException e) {
      }
    }
    if(ps != null) {
      try {
        ps.close();
      } catch (SQLException e) {
      }
    }
    if (c != null) {
      try {
        c.close();
      } catch (SQLException e) {
      }
    }
  }
}
```
- 예외상황에 대한 처리까지 모두 마쳤다.
- 서버환경에서도 안정적으로 수행될 수 있으면서 DB 연결 기능을 자유롭게 확장할 수 있다.
- 하지만 여전히 뭔가 아쉬움이 남아있다.
